routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*---------------------------Front End---------------------------*/

Route::get('/', 'FrontEndController@index')->name('home');                                        // INDEX
Route::get('/contact', 'FrontEndController@contact');                               // CONTACT US

//for register and login user

Route::group(['prefix' => 'user/', 'as' => 'frontend.user.' ], function (){
    Route::get('register',                ['as' => 'register',               'uses' => 'FrontendUserController@register']);
    Route::post('update/{user}',                    ['as' => 'update',                'uses' => 'FrontendUserController@update']);
    Route::get('login',                    ['as' => 'login',                'uses' => 'FrontendUserController@register']);
    Route::post('login',                    ['as' => 'login',                'uses' => 'FrontendUserController@login']);
    Route::post('store',              ['as' => 'store',                  'uses' => 'FrontendUserController@store']);
    Route::get('logout',            ['as' => 'logout',               'uses' => 'FrontendUserController@logout']);
});

//for register and login admin

Route::group(['prefix' => 'admin/', 'as' => 'backend.admin.' ], function (){
    Route::get('register',                ['as' => 'register',               'uses' => 'BackendAdminController@register']);
    Route::get('view',                ['as' => 'view',               'uses' => 'BackendAdminController@view']);
    Route::get('login',                    ['as' => 'login.form',                'uses' => 'BackendAdminController@login_form']);
    Route::post('login',                    ['as' => 'login',                'uses' => 'BackendAdminController@login']);
    Route::post('store',              ['as' => 'store',                  'uses' => 'BackendAdminController@store']);
    Route::get('logout',            ['as' => 'logout',               'uses' => 'BackendAdminController@logout']);
    Route::delete('destroy/{admin}',   ['as' => 'destroy',               'uses' => 'BackendAdminController@destroy']);
});


//for brand in backend
Route::group(['prefix' => 'brand/', 'as' => 'backend.brand.','middleware'=> 'auth:admin' ], function (){
    Route::get('create',                ['as' => 'create',               'uses' => 'BrandController@create']);
    Route::post('store',                    ['as' => 'store',                'uses' => 'BrandController@store']);
    Route::get('view',              ['as' => 'view',                  'uses' => 'BrandController@view']);
    Route::delete('destroy/{manufacturer}',            ['as' => 'destroy',               'uses' => 'BrandController@destroy']);
});

//for category in backend
Route::group(['prefix' => 'category/', 'as' => 'backend.category.','middleware'=> 'auth:admin' ], function (){
    Route::get('create',                ['as' => 'create',               'uses' => 'CategoryController@create']);
    Route::post('store',                    ['as' => 'store',                'uses' => 'CategoryController@store']);
    Route::get('view',              ['as' => 'view',                  'uses' => 'CategoryController@view']);
    Route::delete('destroy/{category}',            ['as' => 'destroy',               'uses' => 'CategoryController@destroy']);
});

//for cart in frontend
Route::group(['prefix' => 'cart/', 'as' => 'frontend.cart.' ], function (){
    //Route::get('create',                ['as' => 'create',               'uses' => 'CategoryController@create']);
    Route::post('store',                  ['as' => 'store',                'uses' => 'CartController@store']);
    Route::post('change/quantity',        ['as' => 'change.quantity',      'uses' => 'CartController@changeQuantity']);
    Route::get('view',                    ['as' => 'view',                  'uses' => 'CartController@view']);
    Route::get('destroy/{cart}',         ['as' => 'destroy',               'uses' => 'CartController@destroy']);
});

Route::post('/customer/order','OrderController@order')->name('frontend.user.order');
Route::get('admin/order','OrderController@view')->name('backend.order.view');
Route::get('admin/order/{order}','OrderController@destroy')->name('backend.order.destroy');


Route::get('/customer-account', 'FrontEndController@customerAccount');              // CUSTOMER ACCOUNT

Route::get('/customer-order', 'FrontEndController@customerOrder');                  // CUSTOMER ORDER DETAIL
Route::get('/customer-orders', 'FrontEndController@customerOrders');                // CUSTOMER ORDERS
Route::get('/customer-wishlist', 'FrontEndController@customerWishlist');            // CUSTOMER WISHLIST

Route::get('/checkout1', 'FrontEndController@checkout1')->name('frontend.user.checkout1');                           // CHECKOUT STEP 1
Route::get('/checkout2', 'FrontEndController@checkout2')->name('frontend.user.checkout2');                           // CHECKOUT STEP 2
Route::get('/checkout3', 'FrontEndController@checkout3')->name('frontend.user.checkout3');                           // CHECKOUT STEP 3
Route::get('/checkout4', 'FrontEndController@checkout4')->name('frontend.user.checkout4');                           // CHECKOUT STEP 4

Route::resource('products', 'ProductsController');                              // Products
Route::get('product/{slug}',['as' => 'product.single',
    'uses' => 'FrontEndController@getSingle'])->where('slug','[\w\d\-]+');      //single product using slug

                                /*----------- For Men Clothing -----------*/
Route::get('/mens-tshirt', 'FrontEndController@menTshirt');                             // Men's T-Shirt
Route::get('/mens-shirt', 'FrontEndController@menShirt');                               // Men's Shirt
Route::get('/mens-pant', 'FrontEndController@menPant');                                 // Men's Pant
Route::get('/mens-coat', 'FrontEndController@menCoat');                                 // Men's Coat
Route::get('/mens-windcheater', 'FrontEndController@menWindCheater');                   // Men's Wind Cheater
Route::get('/mens-jacket', 'FrontEndController@menJacket');                             // Men's Jacket
Route::get('/mens-hoodies', 'FrontEndController@menHoddies');                           // Men's Hoodies
Route::get('/mens-shorts', 'FrontEndController@menShorts');                             // Men's Shorts
Route::get('/mens-socks', 'FrontEndController@menSocks');                               // Men's Socks
                                /*----------- For Men Shoes -----------*/
Route::get('/mens-sport-shoes', 'FrontEndController@menSportShoes');                    // Men's Sport Shoes
Route::get('/mens-casual-shoes', 'FrontEndController@menCasualShoes');                  // Men's Casual Shoes
Route::get('/mens-formal-shoes', 'FrontEndController@menFormalShoes');                  // Men's Formal Shoes
Route::get('/mens-boots', 'FrontEndController@menBoots');                               // Men's boots
Route::get('/mens-sandals-slippers', 'FrontEndController@menSandalsAndSlippers');       // Men's Sandals N Slippers
                                /*----------- For Men Accessories -----------*/
Route::get('/mens-bags', 'FrontEndController@menBags');                                 // Men's Bags
Route::get('/mens-cap-hat-gloves', 'FrontEndController@menCapHatGlove');                // Men's Cap Hat Glove
Route::get('/mens-goggles', 'FrontEndController@menGoggles');                           // Men's Gogs
                                /*----------- For Women Clothing -----------*/
Route::get('/womens-tshirt', 'FrontEndController@womenTshirt');                             // Women's T-Shirt
Route::get('/womens-shirt', 'FrontEndController@womenShirt');                               // Women's Shirt
Route::get('/womens-pant', 'FrontEndController@womenPant');                                 // Women's Pant
Route::get('/womens-coat', 'FrontEndController@womenCoat');                                 // Women's Coat
Route::get('/womens-windcheater', 'FrontEndController@womenWindCheater');                   // Women's Wind Cheater
Route::get('/womens-jacket', 'FrontEndController@womenJacket');                             // Women's Jacket
Route::get('/womens-hoodies', 'FrontEndController@womenHoddies');                           // Women's Hoodies
Route::get('/womens-shorts', 'FrontEndController@womenShorts');                             // Women's Shorts
Route::get('/womens-socks', 'FrontEndController@womenSocks');                               // Women's Socks
                                /*----------- For Women Shoes -----------*/
Route::get('/womens-boots', 'FrontEndController@womenBoots');                               // Women's Boots
Route::get('/womens-sport-shoes', 'FrontEndController@womenSportShoes');                    // Women's Sport Shoes
Route::get('/womens-casual-shoes', 'FrontEndController@womenCasualShoes');                  // Women's Casual Shoes
Route::get('/womens-formal-shoes', 'FrontEndController@womenFormalShoes');                  // Women's Formal Shoes
Route::get('/womens-hiking-shoes', 'FrontEndController@womenHikingShoes');                  // Women's Hiking Shoes
Route::get('/womens-heels', 'FrontEndController@womenHeels');                               // Women's Heels
Route::get('/womens-flats-sandals', 'FrontEndController@womenSandalsAndSlippers');          // Women's Sandals N Flats
                                /*----------- For Women Accessories -----------*/
Route::get('/womens-bags', 'FrontEndController@womenBags');                                 // Women's Bags

resources/views/frontend/contact.blade.php
@extends('layouts.app')

@section('content')
        <div id="content">
            <div class="container">

                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a href="#">Home</a>
                        </li>
                        <li>Contact</li>
                    </ul>

                </div>

                <div class="col-md-3">
                    <!-- *** PAGES MENU ***
 _________________________________________________________ -->
                    <div class="panel panel-default sidebar-menu">

                        <div class="panel-heading">
                            <h3 class="panel-title">Pages</h3>
                        </div>

                        <div class="panel-body">
                            <ul class="nav nav-pills nav-stacked">
                                <li>
                                    <a href="text.html">Text page</a>
                                </li>
                                <li>
                                    <a href="contact.html">Contact page</a>
                                </li>
                                <li>
                                    <a href="faq.html">FAQ</a>
                                </li>

                            </ul>

                        </div>
                    </div>

                    <!-- *** PAGES MENU END *** -->


                    <div class="banner">
                        <a href="#">
                            <img src="img/banner.jpg" alt="sales 2014" class="img-responsive">
                        </a>
                    </div>
                </div>

                <div class="col-md-9">


                    <div class="box" id="contact">
                        <h1>Contact</h1>

                        <p class="lead">Are you curious about something? Do you have some kind of problem with our products?</p>
                        <p>Please feel free to contact us, our customer service center is working for you 24/7.</p>

                        <hr>

                        <div class="row">
                            <div class="col-sm-4">
                                <h3><i class="fa fa-map-marker"></i> Address</h3>
                                <p>13/25 New Avenue
                                    <br>New Heaven
                                    <br>45Y 73J
                                    <br>England
                                    <br>
                                    <strong>Great Britain</strong>
                                </p>
                            </div>
                            <!-- /.col-sm-4 -->
                            <div class="col-sm-4">
                                <h3><i class="fa fa-phone"></i> Call center</h3>
                                <p class="text-muted">This number is toll free if calling from Great Britain otherwise we advise you to use the electronic form of communication.</p>
                                <p><strong>+33 555 444 333</strong>
                                </p>
                            </div>
                            <!-- /.col-sm-4 -->
                            <div class="col-sm-4">
                                <h3><i class="fa fa-envelope"></i> Electronic support</h3>
                                <p class="text-muted">Please feel free to write an email to us or to use our electronic ticketing system.</p>
                                <ul>
                                    <li><strong><a href="mailto:">info@fakeemail.com</a></strong>
                                    </li>
                                    <li><strong><a href="#">Ticketio</a></strong> - our ticketing support platform</li>
                                </ul>
                            </div>
                            <!-- /.col-sm-4 -->
                        </div>
                        <!-- /.row -->

                        <hr>

                        <div id="map">

                        </div>

                        <hr>
                        <h2>Contact form</h2>

                        <form>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="firstname">Firstname</label>
                                        <input type="text" class="form-control" id="firstname">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="lastname">Lastname</label>
                                        <input type="text" class="form-control" id="lastname">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input type="text" class="form-control" id="email">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="subject">Subject</label>
                                        <input type="text" class="form-control" id="subject">
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="message">Message</label>
                                        <textarea id="message" class="form-control"></textarea>
                                    </div>
                                </div>

                                <div class="col-sm-12 text-center">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Send message</button>

                                </div>
                            </div>
                            <!-- /.row -->
                        </form>


                    </div>


                </div>
                <!-- /.col-md-9 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->
@endsection

@section('contactmap')
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>

    <script>
        function initialize() {
            var mapOptions = {
                zoom: 15,
                center: new google.maps.LatLng(49.1678136, 16.5671893),
                mapTypeId: google.maps.MapTypeId.ROAD,
                scrollwheel: false
            }
            var map = new google.maps.Map(document.getElementById('map'),
                mapOptions);

            var myLatLng = new google.maps.LatLng(49.1681989, 16.5650808);
            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map
            });
        }

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
@endsection

resources/views/frontend/register.blade.php
@extends('layouts.app')

    @section('content')

        <div id="content">
            <div class="container">

                <div class="col-md-12">

                    <ul class="breadcrumb">
                        <li><a href="#">Home</a>
                        </li>
                        <li>New account / Sign in</li>
                    </ul>

                </div>

                <div class="col-md-6">
                    <div class="box">
                        <h1>New account</h1>

                        <p class="lead">Not our registered customer yet?</p>
                        <p>With registration with us new world of fashion, fantastic discounts and much more opens to you! The whole process will not take you more than a minute!</p>
                        <p class="text-muted">If you have any questions, please feel free to <a href="contact.html">contact us</a>, our customer service center is working for you 24/7.</p>

                        <hr>
                        @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

                        <form action="{{route('frontend.user.store')}}" method="post">
                        {{ csrf_field() }}
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" name="name" class="form-control" id="name" value="{{old('name')}}" required>
                            </div>

                            <div class="form-group">
                                <label for="username">Username</label>
                                <input type="text" name="username" class="form-control" id="username" value="{{old('username')}}" required>
                            </div>
                            
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" name="email" class="form-control" id="email" value="{{old('email')}}" required>
                            </div>
                            <div class="form-group">
                                <label for="mobile">Mobile</label>
                                <input type="text" name="mobile" class="form-control" id="mobile" value="{{old('mobile')}}" required>
                            </div>
                            <div class="form-group">
                                <label for="address">Address</label>
                                <input type="text" name="address" class="form-control" id="address" value="{{old('address')}}" required>
                            </div>
                            <div class="form-group">
                             <select class="selection-2" name="gender">
                           <option selected="true" disabled="disabled">Gender</option>
							<option value="male">Male</option>
                            <option value="female">Female</option>
						</select>
                        </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" name="password" class="form-control" id="password" required>
                            </div>

                              <div class="form-group">
                                <label for="password">Confirm Password</label>
                                <input type="password" name="password_confirmation" class="form-control" id="password_confirmation" required>
                            </div>
                            <div class="text-center">
                                <button type="submit"  class="btn btn-primary"><i class="fa fa-user-md"></i> Register</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="box">
                        <h1>Login</h1>

                        <p class="lead">Already our customer?</p>
                        <p class="text-muted">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies
                            mi vitae est. Mauris placerat eleifend leo.</p>

                        <hr>
                        @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
                        <form action="{{route('frontend.user.login')}}" method="post">
                        {{ csrf_field() }}
                            <div class="form-group">
                                <label for="username">Username</label>
                                <input type="text" class="form-control" id="username" name="username" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" class="form-control" id="password" name="password" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
                            </div>
                        </form>
                    </div>
                </div>


            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->

    @endsection