routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*---------------------------Front End---------------------------*/

Route::get('/', 'FrontEndController@index')->name('home');                                        // INDEX
Route::get('/contact', 'FrontEndController@contact');                               // CONTACT US

//for register and login user

Route::group(['prefix' => 'user/', 'as' => 'frontend.user.' ], function (){
    Route::get('register',                ['as' => 'register',               'uses' => 'FrontendUserController@register']);
    Route::post('update/{user}',                    ['as' => 'update',                'uses' => 'FrontendUserController@update']);
    Route::get('login',                    ['as' => 'login',                'uses' => 'FrontendUserController@register']);
    Route::post('login',                    ['as' => 'login',                'uses' => 'FrontendUserController@login']);
    Route::post('store',              ['as' => 'store',                  'uses' => 'FrontendUserController@store']);
    Route::get('logout',            ['as' => 'logout',               'uses' => 'FrontendUserController@logout']);
});

//for register and login admin

Route::group(['prefix' => 'admin/', 'as' => 'backend.admin.' ], function (){
    Route::get('register',                ['as' => 'register',               'uses' => 'BackendAdminController@register']);
    Route::get('view',                ['as' => 'view',               'uses' => 'BackendAdminController@view']);
    Route::get('login',                    ['as' => 'login.form',                'uses' => 'BackendAdminController@login_form']);
    Route::post('login',                    ['as' => 'login',                'uses' => 'BackendAdminController@login']);
    Route::post('store',              ['as' => 'store',                  'uses' => 'BackendAdminController@store']);
    Route::get('logout',            ['as' => 'logout',               'uses' => 'BackendAdminController@logout']);
    Route::delete('destroy/{admin}',   ['as' => 'destroy',               'uses' => 'BackendAdminController@destroy']);
});


//for brand in backend
Route::group(['prefix' => 'brand/', 'as' => 'backend.brand.','middleware'=> 'auth:admin' ], function (){
    Route::get('create',                ['as' => 'create',               'uses' => 'BrandController@create']);
    Route::post('store',                    ['as' => 'store',                'uses' => 'BrandController@store']);
    Route::get('view',              ['as' => 'view',                  'uses' => 'BrandController@view']);
    Route::delete('destroy/{manufacturer}',            ['as' => 'destroy',               'uses' => 'BrandController@destroy']);
});

//for category in backend
Route::group(['prefix' => 'category/', 'as' => 'backend.category.','middleware'=> 'auth:admin' ], function (){
    Route::get('create',                ['as' => 'create',               'uses' => 'CategoryController@create']);
    Route::post('store',                    ['as' => 'store',                'uses' => 'CategoryController@store']);
    Route::get('view',              ['as' => 'view',                  'uses' => 'CategoryController@view']);
    Route::delete('destroy/{category}',            ['as' => 'destroy',               'uses' => 'CategoryController@destroy']);
});

//for cart in frontend
Route::group(['prefix' => 'cart/', 'as' => 'frontend.cart.' ], function (){
    //Route::get('create',                ['as' => 'create',               'uses' => 'CategoryController@create']);
    Route::post('store',                  ['as' => 'store',                'uses' => 'CartController@store']);
    Route::post('change/quantity',        ['as' => 'change.quantity',      'uses' => 'CartController@changeQuantity']);
    Route::get('view',                    ['as' => 'view',                  'uses' => 'CartController@view']);
    Route::get('destroy/{cart}',         ['as' => 'destroy',               'uses' => 'CartController@destroy']);
});

Route::post('/customer/order','OrderController@order')->name('frontend.user.order');
Route::get('admin/order','OrderController@view')->name('backend.order.view');
Route::get('admin/order/{order}','OrderController@destroy')->name('backend.order.destroy');


Route::get('/customer-account', 'FrontEndController@customerAccount');              // CUSTOMER ACCOUNT

Route::get('/customer-order', 'FrontEndController@customerOrder');                  // CUSTOMER ORDER DETAIL
Route::get('/customer-orders', 'FrontEndController@customerOrders');                // CUSTOMER ORDERS
Route::get('/customer-wishlist', 'FrontEndController@customerWishlist');            // CUSTOMER WISHLIST

Route::get('/checkout1', 'FrontEndController@checkout1')->name('frontend.user.checkout1');                           // CHECKOUT STEP 1
Route::get('/checkout2', 'FrontEndController@checkout2')->name('frontend.user.checkout2');                           // CHECKOUT STEP 2
Route::get('/checkout3', 'FrontEndController@checkout3')->name('frontend.user.checkout3');                           // CHECKOUT STEP 3
Route::get('/checkout4', 'FrontEndController@checkout4')->name('frontend.user.checkout4');                           // CHECKOUT STEP 4

Route::resource('products', 'ProductsController');                              // Products
Route::get('product/{slug}',['as' => 'product.single',
    'uses' => 'FrontEndController@getSingle'])->where('slug','[\w\d\-]+');      //single product using slug

                                /*----------- For Men Clothing -----------*/
Route::get('/mens-tshirt', 'FrontEndController@menTshirt');                             // Men's T-Shirt
Route::get('/mens-shirt', 'FrontEndController@menShirt');                               // Men's Shirt
Route::get('/mens-pant', 'FrontEndController@menPant');                                 // Men's Pant
Route::get('/mens-coat', 'FrontEndController@menCoat');                                 // Men's Coat
Route::get('/mens-windcheater', 'FrontEndController@menWindCheater');                   // Men's Wind Cheater
Route::get('/mens-jacket', 'FrontEndController@menJacket');                             // Men's Jacket
Route::get('/mens-hoodies', 'FrontEndController@menHoddies');                           // Men's Hoodies
Route::get('/mens-shorts', 'FrontEndController@menShorts');                             // Men's Shorts
Route::get('/mens-socks', 'FrontEndController@menSocks');                               // Men's Socks
                                /*----------- For Men Shoes -----------*/
Route::get('/mens-sport-shoes', 'FrontEndController@menSportShoes');                    // Men's Sport Shoes
Route::get('/mens-casual-shoes', 'FrontEndController@menCasualShoes');                  // Men's Casual Shoes
Route::get('/mens-formal-shoes', 'FrontEndController@menFormalShoes');                  // Men's Formal Shoes
Route::get('/mens-boots', 'FrontEndController@menBoots');                               // Men's boots
Route::get('/mens-sandals-slippers', 'FrontEndController@menSandalsAndSlippers');       // Men's Sandals N Slippers
                                /*----------- For Men Accessories -----------*/
Route::get('/mens-bags', 'FrontEndController@menBags');                                 // Men's Bags
Route::get('/mens-cap-hat-gloves', 'FrontEndController@menCapHatGlove');                // Men's Cap Hat Glove
Route::get('/mens-goggles', 'FrontEndController@menGoggles');                           // Men's Gogs
                                /*----------- For Women Clothing -----------*/
Route::get('/womens-tshirt', 'FrontEndController@womenTshirt');                             // Women's T-Shirt
Route::get('/womens-shirt', 'FrontEndController@womenShirt');                               // Women's Shirt
Route::get('/womens-pant', 'FrontEndController@womenPant');                                 // Women's Pant
Route::get('/womens-coat', 'FrontEndController@womenCoat');                                 // Women's Coat
Route::get('/womens-windcheater', 'FrontEndController@womenWindCheater');                   // Women's Wind Cheater
Route::get('/womens-jacket', 'FrontEndController@womenJacket');                             // Women's Jacket
Route::get('/womens-hoodies', 'FrontEndController@womenHoddies');                           // Women's Hoodies
Route::get('/womens-shorts', 'FrontEndController@womenShorts');                             // Women's Shorts
Route::get('/womens-socks', 'FrontEndController@womenSocks');                               // Women's Socks
                                /*----------- For Women Shoes -----------*/
Route::get('/womens-boots', 'FrontEndController@womenBoots');                               // Women's Boots
Route::get('/womens-sport-shoes', 'FrontEndController@womenSportShoes');                    // Women's Sport Shoes
Route::get('/womens-casual-shoes', 'FrontEndController@womenCasualShoes');                  // Women's Casual Shoes
Route::get('/womens-formal-shoes', 'FrontEndController@womenFormalShoes');                  // Women's Formal Shoes
Route::get('/womens-hiking-shoes', 'FrontEndController@womenHikingShoes');                  // Women's Hiking Shoes
Route::get('/womens-heels', 'FrontEndController@womenHeels');                               // Women's Heels
Route::get('/womens-flats-sandals', 'FrontEndController@womenSandalsAndSlippers');          // Women's Sandals N Flats
                                /*----------- For Women Accessories -----------*/
Route::get('/womens-bags', 'FrontEndController@womenBags');                                 // Women's Bags

app/Http/Controllers/BackEndController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class BackEndController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    public function index(){
        $data = array(
            'title' => 'Admin Panel || Dashboard',
            'product' => Product::all()->first()
        );
        return view('backend.dashboard')->with($data);
    }
    public function getSingle($slug){
       
        $data = array(
            'title' => 'Admin Panel || Product Details',
            'product' => Product::where('slug', '=', $slug)->first()
           
        );
        return view('backend.detail')->with($data);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Category;

class CategoryController extends Controller
{
    public function create(){
        $data = array(
            'title' => 'Admin Panel || Category'
        );
        return view('backend.category.create')->with($data);
    }

    public function store(Request $request){
        $request->validate([
            'name' => 'required|string|max:255'
        ]);

        Category::create([
        'categoryName' => $request['name'],
    ]);
    
    $title = 'Admin Panel || Category';
    
    $category = Category::all();

   //dd($data['size']);
   return view('backend.category.view')->with('title' ,$title)->with('category',$category);
    }

    public function view(){
        
        $title = 'Admin Panel || Category';
 
      $category = Category::all();
      //dd($brand);

     //dd($data['size']);
     return view('backend.category.view')->with('title' ,$title)->with('category',$category);
 }

 public function destroy(Category $category)
    {
        $category_del = Category::where('categoryId', $category->categoryId)->first();
        if($category_del){
        $category_del->delete();
        }
        return redirect()->route('backend.category.view');
    }
}

resources/views/backend/category/create.blade.php
@extends('layouts.backapp')

@section('content')
    <h3 class="header smaller lighter blue">Add Cateogry Below:</h3>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form class="form-horizontal" role="form" action="{{route("backend.category.store")}}" method="post" id="add-product">
        {{ csrf_field() }}

        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Category Name </label>
            <div class="col-sm-9">
                <input name="name" value="" type="text" id="form-field-1" placeholder="Category Name" class="col-xs-10 col-sm-5" />
            </div>
        </div>

         <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> </label>
            <div class="col-sm-9">
                <button type="submit" form="add-product" value="submit" class="btn btn-white btn-info btn-bold">
                    <i class="ace-icon fa fa-floppy-o bigger-120 blue"></i>
                    Add Category
                </button>
            </div>
        </div>

    </form>
    <script src="{{ asset('tinymce/tinymce.min.js') }}"></script>
    <script>
        var editor_config = {
            path_absolute : "{{ URL::to('/') }}/",
            selector: "textarea",
            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
            relative_urls: false,
            file_browser_callback : function(field_name, url, type, win) {
                var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
                var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;
                var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
                if (type == 'image') {
                    cmsURL = cmsURL + "&type=Images";
                } else {
                    cmsURL = cmsURL + "&type=Files";
                }
                tinyMCE.activeEditor.windowManager.open({
                    file : cmsURL,
                    title : 'Filemanager',
                    width : x * 0.8,
                    height : y * 0.8,
                    resizable : "yes",
                    close_previous : "no"
                });
            }
        };
        tinymce.init(editor_config);


    </script>
@endsection

resources/views/backend/category/view.blade.php
@extends('layouts.backapp')

    @section('content')

   
   
        <h3 class="header smaller lighter blue">Your Category</h3>

        <div class="clearfix">
            <div class="pull-right tableTools-container"></div>
        </div>
        {{--<div class="table-header">--}}
            {{--Results for "Latest Registered Domains"--}}
        {{--</div>--}}

        <!-- div.table-responsive -->

        <!-- div.dataTables_borderWrap -->
        <div>
            <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th>Category Name</th>
                    <th>Action</th>
                </tr>
                </thead>

                <tbody>
                @if(count($category) > 0)
                    @foreach($category as $category)
                        <tr>
                         

                            <td>
                                <a href="">{{ $category->categoryName }}</a>
                            </td>
                            <td>
                            {!! Form::open(['method' => 'DELETE', 'route' => ['backend.category.destroy', $category->categoryId]]) !!}
                  {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                  {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                @endif

                </tbody>
            </table>
        </div>
    @endsection

    @section('inlinescript')

        <!-- page specific plugin scripts -->
        <script src="{{asset('assets/js/jquery.dataTables.min.js')}}"></script>
        <script src="{{asset('assets/js/jquery.dataTables.bootstrap.min.js')}}"></script>
        <script src="{{asset('assets/js/dataTables.buttons.min.js')}}"></script>
        <script src="{{asset('assets/js/buttons.flash.min.js')}}"></script>
        <script src="{{asset('assets/js/buttons.html5.min.js')}}"></script>
        <script src="{{asset('assets/js/buttons.print.min.js')}}"></script>
        <script src="{{asset('assets/js/buttons.colVis.min.js')}}"></script>
        <script src="{{asset('assets/js/dataTables.select.min.js')}}"></script>

        <!-- inline scripts related to this page -->
        <script type="text/javascript">
            jQuery(function($) {
                //initiate dataTables plugin
                var myTable =
                    $('#dynamic-table')
                    //.wrap("<div class='dataTables_borderWrap' />")   //if you are applying horizontal scrolling (sScrollX)
                        .DataTable( {
                            bAutoWidth: false,
                            "aoColumns": [
                                { "bSortable": false },
                                null, null,null, null, null,
                                { "bSortable": false }
                            ],
                            "aaSorting": [],


                            //"bProcessing": true,
                            //"bServerSide": true,
                            //"sAjaxSource": "http://127.0.0.1/table.php"	,

                            //,
                            //"sScrollY": "200px",
                            //"bPaginate": false,

                            //"sScrollX": "100%",
                            //"sScrollXInner": "120%",
                            //"bScrollCollapse": true,
                            //Note: if you are applying horizontal scrolling (sScrollX) on a ".table-bordered"
                            //you may want to wrap the table inside a "div.dataTables_borderWrap" element

                            //"iDisplayLength": 50


                            select: {
                                style: 'multi'
                            }
                        } );



                $.fn.dataTable.Buttons.defaults.dom.container.className = 'dt-buttons btn-overlap btn-group btn-overlap';

                new $.fn.dataTable.Buttons( myTable, {
                    buttons: [
                        {
                            "extend": "colvis",
                            "text": "<i class='fa fa-search bigger-110 blue'></i> <span class='hidden'>Show/hide columns</span>",
                            "className": "btn btn-white btn-primary btn-bold",
                            columns: ':not(:first):not(:last)'
                        },
                        {
                            "extend": "copy",
                            "text": "<i class='fa fa-copy bigger-110 pink'></i> <span class='hidden'>Copy to clipboard</span>",
                            "className": "btn btn-white btn-primary btn-bold"
                        },
                        {
                            "extend": "csv",
                            "text": "<i class='fa fa-database bigger-110 orange'></i> <span class='hidden'>Export to CSV</span>",
                            "className": "btn btn-white btn-primary btn-bold"
                        },
                        {
                            "extend": "excel",
                            "text": "<i class='fa fa-file-excel-o bigger-110 green'></i> <span class='hidden'>Export to Excel</span>",
                            "className": "btn btn-white btn-primary btn-bold"
                        },
                        {
                            "extend": "pdf",
                            "text": "<i class='fa fa-file-pdf-o bigger-110 red'></i> <span class='hidden'>Export to PDF</span>",
                            "className": "btn btn-white btn-primary btn-bold"
                        },
                        {
                            "extend": "print",
                            "text": "<i class='fa fa-print bigger-110 grey'></i> <span class='hidden'>Print</span>",
                            "className": "btn btn-white btn-primary btn-bold",
                            autoPrint: false,
                            message: 'This print was produced using the Print button for DataTables'
                        }
                    ]
                } );
                myTable.buttons().container().appendTo( $('.tableTools-container') );

                //style the message box
                var defaultCopyAction = myTable.button(1).action();
                myTable.button(1).action(function (e, dt, button, config) {
                    defaultCopyAction(e, dt, button, config);
                    $('.dt-button-info').addClass('gritter-item-wrapper gritter-info gritter-center white');
                });


                var defaultColvisAction = myTable.button(0).action();
                myTable.button(0).action(function (e, dt, button, config) {

                    defaultColvisAction(e, dt, button, config);


                    if($('.dt-button-collection > .dropdown-menu').length == 0) {
                        $('.dt-button-collection')
                            .wrapInner('<ul class="dropdown-menu dropdown-light dropdown-caret dropdown-caret" />')
                            .find('a').attr('href', '#').wrap("<li />")
                    }
                    $('.dt-button-collection').appendTo('.tableTools-container .dt-buttons')
                });

                ////

                setTimeout(function() {
                    $($('.tableTools-container')).find('a.dt-button').each(function() {
                        var div = $(this).find(' > div').first();
                        if(div.length == 1) div.tooltip({container: 'body', title: div.parent().text()});
                        else $(this).tooltip({container: 'body', title: $(this).text()});
                    });
                }, 500);





                myTable.on( 'select', function ( e, dt, type, index ) {
                    if ( type === 'row' ) {
                        $( myTable.row( index ).node() ).find('input:checkbox').prop('checked', true);
                    }
                } );
                myTable.on( 'deselect', function ( e, dt, type, index ) {
                    if ( type === 'row' ) {
                        $( myTable.row( index ).node() ).find('input:checkbox').prop('checked', false);
                    }
                } );




                /////////////////////////////////
                //table checkboxes
                $('th input[type=checkbox], td input[type=checkbox]').prop('checked', false);

                //select/deselect all rows according to table header checkbox
                $('#dynamic-table > thead > tr > th input[type=checkbox], #dynamic-table_wrapper input[type=checkbox]').eq(0).on('click', function(){
                    var th_checked = this.checked;//checkbox inside "TH" table header

                    $('#dynamic-table').find('tbody > tr').each(function(){
                        var row = this;
                        if(th_checked) myTable.row(row).select();
                        else  myTable.row(row).deselect();
                    });
                });

                //select/deselect a row when the checkbox is checked/unchecked
                $('#dynamic-table').on('click', 'td input[type=checkbox]' , function(){
                    var row = $(this).closest('tr').get(0);
                    if(this.checked) myTable.row(row).deselect();
                    else myTable.row(row).select();
                });



                $(document).on('click', '#dynamic-table .dropdown-toggle', function(e) {
                    e.stopImmediatePropagation();
                    e.stopPropagation();
                    e.preventDefault();
                });



                //And for the first simple table, which doesn't have TableTools or dataTables
                //select/deselect all rows according to table header checkbox
                var active_class = 'active';
                $('#simple-table > thead > tr > th input[type=checkbox]').eq(0).on('click', function(){
                    var th_checked = this.checked;//checkbox inside "TH" table header

                    $(this).closest('table').find('tbody > tr').each(function(){
                        var row = this;
                        if(th_checked) $(row).addClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', true);
                        else $(row).removeClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', false);
                    });
                });

                //select/deselect a row when the checkbox is checked/unchecked
                $('#simple-table').on('click', 'td input[type=checkbox]' , function(){
                    var $row = $(this).closest('tr');
                    if($row.is('.detail-row ')) return;
                    if(this.checked) $row.addClass(active_class);
                    else $row.removeClass(active_class);
                });



                /********************************/
                //add tooltip for small view action buttons in dropdown menu
                $('[data-rel="tooltip"]').tooltip({placement: tooltip_placement});

                //tooltip placement on right or left
                function tooltip_placement(context, source) {
                    var $source = $(source);
                    var $parent = $source.closest('table')
                    var off1 = $parent.offset();
                    var w1 = $parent.width();

                    var off2 = $source.offset();
                    //var w2 = $source.width();

                    if( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';
                    return 'left';
                }




                /***************/
                $('.show-details-btn').on('click', function(e) {
                    e.preventDefault();
                    $(this).closest('tr').next().toggleClass('open');
                    $(this).find(ace.vars['.icon']).toggleClass('fa-angle-double-down').toggleClass('fa-angle-double-up');
                });
                /***************/





                /**
                 //add horizontal scrollbars to a simple table
                 $('#simple-table').css({'width':'2000px', 'max-width': 'none'}).wrap('<div style="width: 1000px;" />').parent().ace_scroll(
                 {
                   horizontal: true,
                   styleClass: 'scroll-top scroll-dark scroll-visible',//show the scrollbars on top(default is bottom)
                   size: 2000,
                   mouseWheelLock: true
                 }
                 ).css('padding-top', '12px');
                 */


            })
        </script>
    @endsection