routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*---------------------------Front End---------------------------*/

Route::get('/', 'FrontEndController@index')->name('home');                                        // INDEX
Route::get('/contact', 'FrontEndController@contact');                               // CONTACT US

//for register and login user

Route::group(['prefix' => 'user/', 'as' => 'frontend.user.' ], function (){
    Route::get('register',                ['as' => 'register',               'uses' => 'FrontendUserController@register']);
    Route::post('update/{user}',                    ['as' => 'update',                'uses' => 'FrontendUserController@update']);
    Route::get('login',                    ['as' => 'login',                'uses' => 'FrontendUserController@register']);
    Route::post('login',                    ['as' => 'login',                'uses' => 'FrontendUserController@login']);
    Route::post('store',              ['as' => 'store',                  'uses' => 'FrontendUserController@store']);
    Route::get('logout',            ['as' => 'logout',               'uses' => 'FrontendUserController@logout']);
});

//for register and login admin

Route::group(['prefix' => 'admin/', 'as' => 'backend.admin.' ], function (){
    Route::get('register',                ['as' => 'register',               'uses' => 'BackendAdminController@register']);
    Route::get('view',                ['as' => 'view',               'uses' => 'BackendAdminController@view']);
    Route::get('login',                    ['as' => 'login.form',                'uses' => 'BackendAdminController@login_form']);
    Route::post('login',                    ['as' => 'login',                'uses' => 'BackendAdminController@login']);
    Route::post('store',              ['as' => 'store',                  'uses' => 'BackendAdminController@store']);
    Route::get('logout',            ['as' => 'logout',               'uses' => 'BackendAdminController@logout']);
    Route::delete('destroy/{admin}',   ['as' => 'destroy',               'uses' => 'BackendAdminController@destroy']);
});


//for brand in backend
Route::group(['prefix' => 'brand/', 'as' => 'backend.brand.','middleware'=> 'auth:admin' ], function (){
    Route::get('create',                ['as' => 'create',               'uses' => 'BrandController@create']);
    Route::post('store',                    ['as' => 'store',                'uses' => 'BrandController@store']);
    Route::get('view',              ['as' => 'view',                  'uses' => 'BrandController@view']);
    Route::delete('destroy/{manufacturer}',            ['as' => 'destroy',               'uses' => 'BrandController@destroy']);
});

//for category in backend
Route::group(['prefix' => 'category/', 'as' => 'backend.category.','middleware'=> 'auth:admin' ], function (){
    Route::get('create',                ['as' => 'create',               'uses' => 'CategoryController@create']);
    Route::post('store',                    ['as' => 'store',                'uses' => 'CategoryController@store']);
    Route::get('view',              ['as' => 'view',                  'uses' => 'CategoryController@view']);
    Route::delete('destroy/{category}',            ['as' => 'destroy',               'uses' => 'CategoryController@destroy']);
});

//for cart in frontend
Route::group(['prefix' => 'cart/', 'as' => 'frontend.cart.' ], function (){
    //Route::get('create',                ['as' => 'create',               'uses' => 'CategoryController@create']);
    Route::post('store',                  ['as' => 'store',                'uses' => 'CartController@store']);
    Route::post('change/quantity',        ['as' => 'change.quantity',      'uses' => 'CartController@changeQuantity']);
    Route::get('view',                    ['as' => 'view',                  'uses' => 'CartController@view']);
    Route::get('destroy/{cart}',         ['as' => 'destroy',               'uses' => 'CartController@destroy']);
});

Route::post('/customer/order','OrderController@order')->name('frontend.user.order');
Route::get('admin/order','OrderController@view')->name('backend.order.view');
Route::get('admin/order/{order}','OrderController@destroy')->name('backend.order.destroy');


Route::get('/customer-account', 'FrontEndController@customerAccount');              // CUSTOMER ACCOUNT

Route::get('/customer-order', 'FrontEndController@customerOrder');                  // CUSTOMER ORDER DETAIL
Route::get('/customer-orders', 'FrontEndController@customerOrders');                // CUSTOMER ORDERS
Route::get('/customer-wishlist', 'FrontEndController@customerWishlist');            // CUSTOMER WISHLIST

Route::get('/checkout1', 'FrontEndController@checkout1')->name('frontend.user.checkout1');                           // CHECKOUT STEP 1
Route::get('/checkout2', 'FrontEndController@checkout2')->name('frontend.user.checkout2');                           // CHECKOUT STEP 2
Route::get('/checkout3', 'FrontEndController@checkout3')->name('frontend.user.checkout3');                           // CHECKOUT STEP 3
Route::get('/checkout4', 'FrontEndController@checkout4')->name('frontend.user.checkout4');                           // CHECKOUT STEP 4

Route::resource('products', 'ProductsController');                              // Products
Route::get('product/{slug}',['as' => 'product.single',
    'uses' => 'FrontEndController@getSingle'])->where('slug','[\w\d\-]+');      //single product using slug

                                /*----------- For Men Clothing -----------*/
Route::get('/mens-tshirt', 'FrontEndController@menTshirt');                             // Men's T-Shirt
Route::get('/mens-shirt', 'FrontEndController@menShirt');                               // Men's Shirt
Route::get('/mens-pant', 'FrontEndController@menPant');                                 // Men's Pant
Route::get('/mens-coat', 'FrontEndController@menCoat');                                 // Men's Coat
Route::get('/mens-windcheater', 'FrontEndController@menWindCheater');                   // Men's Wind Cheater
Route::get('/mens-jacket', 'FrontEndController@menJacket');                             // Men's Jacket
Route::get('/mens-hoodies', 'FrontEndController@menHoddies');                           // Men's Hoodies
Route::get('/mens-shorts', 'FrontEndController@menShorts');                             // Men's Shorts
Route::get('/mens-socks', 'FrontEndController@menSocks');                               // Men's Socks
                                /*----------- For Men Shoes -----------*/
Route::get('/mens-sport-shoes', 'FrontEndController@menSportShoes');                    // Men's Sport Shoes
Route::get('/mens-casual-shoes', 'FrontEndController@menCasualShoes');                  // Men's Casual Shoes
Route::get('/mens-formal-shoes', 'FrontEndController@menFormalShoes');                  // Men's Formal Shoes
Route::get('/mens-boots', 'FrontEndController@menBoots');                               // Men's boots
Route::get('/mens-sandals-slippers', 'FrontEndController@menSandalsAndSlippers');       // Men's Sandals N Slippers
                                /*----------- For Men Accessories -----------*/
Route::get('/mens-bags', 'FrontEndController@menBags');                                 // Men's Bags
Route::get('/mens-cap-hat-gloves', 'FrontEndController@menCapHatGlove');                // Men's Cap Hat Glove
Route::get('/mens-goggles', 'FrontEndController@menGoggles');                           // Men's Gogs
                                /*----------- For Women Clothing -----------*/
Route::get('/womens-tshirt', 'FrontEndController@womenTshirt');                             // Women's T-Shirt
Route::get('/womens-shirt', 'FrontEndController@womenShirt');                               // Women's Shirt
Route::get('/womens-pant', 'FrontEndController@womenPant');                                 // Women's Pant
Route::get('/womens-coat', 'FrontEndController@womenCoat');                                 // Women's Coat
Route::get('/womens-windcheater', 'FrontEndController@womenWindCheater');                   // Women's Wind Cheater
Route::get('/womens-jacket', 'FrontEndController@womenJacket');                             // Women's Jacket
Route::get('/womens-hoodies', 'FrontEndController@womenHoddies');                           // Women's Hoodies
Route::get('/womens-shorts', 'FrontEndController@womenShorts');                             // Women's Shorts
Route::get('/womens-socks', 'FrontEndController@womenSocks');                               // Women's Socks
                                /*----------- For Women Shoes -----------*/
Route::get('/womens-boots', 'FrontEndController@womenBoots');                               // Women's Boots
Route::get('/womens-sport-shoes', 'FrontEndController@womenSportShoes');                    // Women's Sport Shoes
Route::get('/womens-casual-shoes', 'FrontEndController@womenCasualShoes');                  // Women's Casual Shoes
Route::get('/womens-formal-shoes', 'FrontEndController@womenFormalShoes');                  // Women's Formal Shoes
Route::get('/womens-hiking-shoes', 'FrontEndController@womenHikingShoes');                  // Women's Hiking Shoes
Route::get('/womens-heels', 'FrontEndController@womenHeels');                               // Women's Heels
Route::get('/womens-flats-sandals', 'FrontEndController@womenSandalsAndSlippers');          // Women's Sandals N Flats
                                /*----------- For Women Accessories -----------*/
Route::get('/womens-bags', 'FrontEndController@womenBags');                                 // Women's Bags

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Model\User;
use App\Model\Cart;
use App\Model\Order;

class OrderController extends Controller
{
    public function order(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'mobile' => 'required|digits:10',
            'city' => 'required',
            'street' => 'required',
            'email' => 'required|max:30',
        ]);


        $user_id = auth()->user()->id;
        $cart = User::find($user_id)->carts;

        foreach($cart as $cart)
        { 
            $exist_order = Order::where('cart_id', $cart->id)->where('user_id', $user_id)->get();
            $cart_id = $cart->id;
            if(count($exist_order) == 0){
            $order = Order::create([
                'name' => $request['name'],
                'mobile' => $request['mobile'],
                'city' => $request['city'],
                'street' => $request['street'],
                'email' => $request['email'],
                'user_id' => $user_id,
                'cart_id' => $cart_id,
            ]);
            Cart::where('id', $cart_id)
            ->update(['status' => 1]);

            }
          

        }
       
   return redirect()->route('home');
    
    }



    public function view()
    {
     $title = "Orders";   
    $order = Order::get();
    // dd($order);
    // foreach($order as $order)
    // $product = $order->carts->products;
    // dd($product);
    return view('backend.order.view')->with('title', $title)->with('order',$order);

    }

    public function destroy(Order $order)
    {
        $order_del = Order::where('id', $order->id)->first();
        if($order_del){
        $order_del->delete();
        }
        
     $title = "Orders";   
    $order = Order::get();
    // dd($order);
    // foreach($order as $order)
    // $product = $order->carts->products;
    // dd($product);
    return view('backend.order.view')->with('title', $title)->with('order',$order);

    }


}

resources/views/frontend/order/cart.blade.php
@extends('layouts.app')

    @section('content')
        <div id="content">
            <div class="container">

                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a href="#">Home</a>
                        </li>
                        <li>Shopping cart</li>
                    </ul>
                </div>

                <div class="col-md-9" id="basket">

                    <div class="box">

                      

                            <h1>Shopping cart</h1>
                            <p class="text-muted">You currently have 3 item(s) in your cart.</p>
                            <div  class="table-responsive">
                                <table  class="table">
                                    <thead>
                                        <tr>
                                      
                                            <th>Product</th>
                                            <th></th>
                                            <th>Size</th>
                                            <th>Color</th>
                                            <th>Quantity</th>
                                            <th>Unit price</th>
                                   
                                            <th>Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($cart as $cart)
                                        <tr>
                                            <td>
                                                <a href="#">
                                                    <img src="{{asset('images/products/'.$cart->products->image1)}}" alt="White Blouse Armani">
                                                </a>
                                            </td>
                                            <td><a href="#">{{$cart->products->productName}}</a>
                                            </td>
                                            <td>{{$cart->sizes->name}}</td>
                                            <td>{{$cart->colors->name}}</td>
                                            <td>
                                                <input id="quantity{{$cart->id}}" onchange="quantityChange({{$cart->id}})" type="number" value="{{$cart->quantity}}" class="form-control" min="1">
                                            </td>
                                            <td>
                                            {{$cart->products->productPrice}}
                                            </td>
                                            <td id="quantityprice{{$cart->id}}">{{$cart->price}}</td>
                                       
                                            <td></td>
                                            <td><a href="{{route('frontend.cart.destroy', $cart->id)}}"><i class="fa fa-trash-o"></i></a>
                                           
                                            </td>
                                        </tr>
                                 @endforeach
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th colspan="5">Total</th>
                                            <th id="totalprice" colspan="2" >NRS {{$totalprice}}</th>
                                        </tr>
                                    </tfoot>
                                </table>

                            </div>
                            <!-- /.table-responsive -->

                            <div class="box-footer">
                                <div class="pull-left">
                                    <a href="category.html" class="btn btn-default"><i class="fa fa-chevron-left"></i> Continue shopping</a>
                                </div>
                                <div class="pull-right">
                                <a href="{{route('frontend.user.checkout1')}}" class="btn btn-primary">Proceed to Checkout<i class="fa fa-chevron-right"></i></a>
                                   
                                </div>
                            </div>

                        </form>

                    </div>
                    <!-- /.box -->


                    <div class="row same-height-row">
                        <div class="col-md-3 col-sm-6">
                            <div class="box same-height">
                                <h3>You may also like these products</h3>
                            </div>
                        </div>

                        <div class="col-md-3 col-sm-6">
                            <div class="product same-height">
                                <div class="flip-container">
                                    <div class="flipper">
                                        <div class="front">
                                            <a href="detail.html">
                                                <img src="img/product2.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                        <div class="back">
                                            <a href="detail.html">
                                                <img src="img/product2_2.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a href="detail.html" class="invisible">
                                    <img src="img/product2.jpg" alt="" class="img-responsive">
                                </a>
                                <div class="text">
                                    <h3>Fur coat</h3>
                                    <p class="price">$143</p>
                                </div>
                            </div>
                            <!-- /.product -->
                        </div>

                        <div class="col-md-3 col-sm-6">
                            <div class="product same-height">
                                <div class="flip-container">
                                    <div class="flipper">
                                        <div class="front">
                                            <a href="detail.html">
                                                <img src="img/product1.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                        <div class="back">
                                            <a href="detail.html">
                                                <img src="img/product1_2.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a href="detail.html" class="invisible">
                                    <img src="img/product1.jpg" alt="" class="img-responsive">
                                </a>
                                <div class="text">
                                    <h3>Fur coat</h3>
                                    <p class="price">$143</p>
                                </div>
                            </div>
                            <!-- /.product -->
                        </div>


                        <div class="col-md-3 col-sm-6">
                            <div class="product same-height">
                                <div class="flip-container">
                                    <div class="flipper">
                                        <div class="front">
                                            <a href="detail.html">
                                                <img src="img/product3.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                        <div class="back">
                                            <a href="detail.html">
                                                <img src="img/product3_2.jpg" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a href="detail.html" class="invisible">
                                    <img src="img/product3.jpg" alt="" class="img-responsive">
                                </a>
                                <div class="text">
                                    <h3>Fur coat</h3>
                                    <p class="price">$143</p>

                                </div>
                            </div>
                            <!-- /.product -->
                        </div>

                    </div>


                </div>
                <!-- /.col-md-9 -->

                <div class="col-md-3">
                    <div class="box" id="order-summary">
                        <div class="box-header">
                            <h3>Order summary</h3>
                        </div>
                        <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Order subtotal</td>
                                        <th colspan="2" id="totalprice">NRS {{$totalprice}}</th>
                                    </tr>
                                    <tr>
                                        <td>Shipping and handling</td>
                                        <th>$10.00</th>
                                    </tr>
                                    <tr>
                                        <td>Tax</td>
                                        <th>$0.00</th>
                                    </tr>
                                    <tr class="total">
                                        <td>Total</td>
                                        <th colspan="2" id="totalprice">NRS {{$totalprice}}</th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>


                    <div class="box">
                        <div class="box-header">
                            <h4>Coupon code</h4>
                        </div>
                        <p class="text-muted">If you have a coupon code, please enter it in the box below.</p>
                        <form>
                            <div class="input-group">

                                <input type="text" class="form-control">

                                <span class="input-group-btn">

					<button class="btn btn-primary" type="button"><i class="fa fa-gift"></i></button>

				    </span>
                            </div>
                            <!-- /input-group -->
                        </form>
                    </div>

                </div>
                <!-- /.col-md-3 -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->
    @endsection

resources/views/frontend/order/checkout2.blade.php
@extends('layouts.app')

    @section('content')
        <div id="content">
            <div class="container">

                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a href="#">Home</a>
                        </li>
                        <li>Checkout - Delivery method</li>
                    </ul>
                </div>

                <div class="col-md-9" id="checkout">

                    <div class="box">
                        <form method="post" action="checkout3.blade.php">
                            <h1>Checkout - Delivery method</h1>
                            <ul class="nav nav-pills nav-justified">
                                <li><a href="checkout1.blade.php"><i class="fa fa-map-marker"></i><br>Address</a>
                                </li>
                                <li class="active"><a href="#"><i class="fa fa-truck"></i><br>Delivery Method</a>
                                </li>
                                <li class="disabled"><a href="#"><i class="fa fa-money"></i><br>Payment Method</a>
                                </li>
                                <li class="disabled"><a href="#"><i class="fa fa-eye"></i><br>Order Review</a>
                                </li>
                            </ul>

                            <div class="content">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="box shipping-method">

                                            <h4>USPS Next Day</h4>

                                            <p>Get it right on next day - fastest option possible.</p>

                                            <div class="box-footer text-center">

                                                <input type="radio" name="delivery" value="delivery1">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="box shipping-method">

                                            <h4>USPS Next Day</h4>

                                            <p>Get it right on next day - fastest option possible.</p>

                                            <div class="box-footer text-center">

                                                <input type="radio" name="delivery" value="delivery2">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-6">
                                        <div class="box shipping-method">

                                            <h4>USPS Next Day</h4>

                                            <p>Get it right on next day - fastest option possible.</p>

                                            <div class="box-footer text-center">

                                                <input type="radio" name="delivery" value="delivery3">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.row -->

                            </div>
                            <!-- /.content -->

                            <div class="box-footer">
                                <div class="pull-left">
                                    <a href="cart.blade.php" class="btn btn-default"><i class="fa fa-chevron-left"></i>Back to Addresses</a>
                                </div>
                                <div class="pull-right">
                                    <button type="submit" class="btn btn-primary">Continue to Payment Method<i class="fa fa-chevron-right"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->


                </div>
                <!-- /.col-md-9 -->

                <div class="col-md-3">

                    <div class="box" id="order-summary">
                        <div class="box-header">
                            <h3>Order summary</h3>
                        </div>
                        <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>Order subtotal</td>
                                        <th>$446.00</th>
                                    </tr>
                                    <tr>
                                        <td>Shipping and handling</td>
                                        <th>$10.00</th>
                                    </tr>
                                    <tr>
                                        <td>Tax</td>
                                        <th>$0.00</th>
                                    </tr>
                                    <tr class="total">
                                        <td>Total</td>
                                        <th>$456.00</th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>

                </div>
                <!-- /.col-md-3 -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->
    @endsection